channels:
- conda-forge
dependencies:
- python=3.13.9
- pip<=24.3.1
- pip:
  - mlflow==3.2.0
  - cloudpickle==3.1.1
  - numpy==2.3.4
  - packaging==25.0
  - pandas==2.3.2
  - pyarrow==21.0.0
  - pyyaml==6.0.3
  - scikit-learn==1.7.2
  - scipy==1.16.3
name: mlflow-env
