_wandb:
    value:
        cli_version: 0.21.3
        e:
            utnormvccy56ykuqn0o932vannrcha5h:
                args:
                    - --input_artifact
                    - preprocessed_data.csv:latest
                    - --artifact_root
                    - data
                    - --artifact_type
                    - segregated_data
                    - --test_size
                    - "0.3"
                    - --random_state
                    - "42"
                    - --stratify
                    - genre
                codePath: segregate/run.py
                codePathLocal: run.py
                cpu_count: 6
                cpu_count_logical: 12
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "1081101176832"
                        used: "23021678592"
                email: caleb.poock@gmail.com
                executable: /home/teqqqie/miniconda3/envs/mlflow-2b05c334639a6588d5c96ec48ecc7de59f6ca254/bin/python
                git:
                    commit: 6abe5c89432961258b8b23381bb09b6d7db7a61b
                    remote: https://github.com/teqqqie/genre_classification
                gpu: NVIDIA GeForce RTX 2060
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Turing
                      memoryTotal: "6442450944"
                      name: NVIDIA GeForce RTX 2060
                      uuid: GPU-d20e5bde-8945-eb88-02df-135f44ffffa8
                host: TEQQQIE-OMEN
                memory:
                    total: "6127030272"
                os: Linux-6.6.87.2-microsoft-standard-WSL2-x86_64-with-glibc2.39
                program: /home/teqqqie/D501-Exercises/lesson-5-final-pipeline-release-and-deploy/genre_classification/segregate/run.py
                python: CPython 3.13.9
                root: /home/teqqqie/D501-Exercises/lesson-5-final-pipeline-release-and-deploy/genre_classification/segregate
                startedAt: "2025-10-31T17:47:41.944961Z"
                writerId: utnormvccy56ykuqn0o932vannrcha5h
        m: []
        python_version: 3.13.9
        t:
            "1":
                - 5
                - 53
            "2":
                - 5
                - 53
            "4": 3.13.9
            "5": 0.21.3
            "12": 0.21.3
            "13": linux-x86_64
