_wandb:
    value:
        cli_version: 0.21.3
        e:
            l14xjs809rswszkjmmtsuk4edj2j6gxv:
                args:
                    - --input_artifact
                    - raw_data.parquet:latest
                    - --artifact_name
                    - preprocessed_data.csv
                    - --artifact_type
                    - preprocessed_data
                    - --artifact_description
                    - Preprocessed data
                codePath: preprocess/run.py
                codePathLocal: run.py
                cpu_count: 6
                cpu_count_logical: 12
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "1081101176832"
                        used: "23038312448"
                email: caleb.poock@gmail.com
                executable: /home/teqqqie/miniconda3/envs/mlflow-428f3442275814dbf6350cf02d74496ce6bae3ac/bin/python
                git:
                    commit: 6abe5c89432961258b8b23381bb09b6d7db7a61b
                    remote: https://github.com/teqqqie/genre_classification
                gpu: NVIDIA GeForce RTX 2060
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Turing
                      memoryTotal: "6442450944"
                      name: NVIDIA GeForce RTX 2060
                      uuid: GPU-d20e5bde-8945-eb88-02df-135f44ffffa8
                host: TEQQQIE-OMEN
                memory:
                    total: "6127030272"
                os: Linux-6.6.87.2-microsoft-standard-WSL2-x86_64-with-glibc2.39
                program: /home/teqqqie/D501-Exercises/lesson-5-final-pipeline-release-and-deploy/genre_classification/preprocess/run.py
                python: CPython 3.13.9
                root: /home/teqqqie/D501-Exercises/lesson-5-final-pipeline-release-and-deploy/genre_classification/preprocess
                startedAt: "2025-10-31T17:57:13.570302Z"
                writerId: l14xjs809rswszkjmmtsuk4edj2j6gxv
        m: []
        python_version: 3.13.9
        t:
            "4": 3.13.9
            "5": 0.21.3
            "12": 0.21.3
            "13": linux-x86_64
