name: download_data
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.13
  - pandas=2.3.2
  - pip=24.3.1
  - scikit-learn=1.7.2
  - matplotlib==3.10.6
  - plotly=6.3.0
  - pillow=11.3.0
  - mlflow=3.2.0
  - pip:
      - wandb==0.21.3